### ISSUE TITLE
Unable to use it with on-prem SQL Server

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/sql-action#111]
Hello!

I'm trying to use this action to deploy some SQL Script to a SQL Container which is spin up as a `services` container at build time so we can validate the build with unit tests on Github Enterprise on a self-hosted GitHub Actions agent.

The SQL container is defined like this:

```
    services:
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: yourStrong(!)Password
        ports:
          - 1433
```

The  actions setup is as follow:

```
- uses: azure/sql-action@v1.3
        with:        
          connection-string: ${{ env.SQL_CS }}
          sql-file: 'src/*.sql'
        env:
          SQL_CS: "Server=localhost,${{ job.services.sql.ports[1433] }};Initial Catalog=MyDB;User Id=sa;Password=yourStrong(!)Password"
```

The error is shown like this:

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/4714040/182504872-839510d0-62f6-4a9b-95fe-d7c9aa0966ce.png">

Am I missing something? The readme says it is supposed to work with SQL Server, not just with Azure SQL. Can someone shed a light on it?

Thanks!

**Comment by dzsquared** [comment]
@galvesribeiro - I suspect that the issue here is the sidecar/services container is still starting up when the sql-action step tries to execute against it.

The below example includes a step to wait for the SQL engine in the container to be ready for connections.


```yaml

    # service/sidecar container for azure-sql-edge
    services:
      mssql:
        image: mcr.microsoft.com/azure-sql-edge:latest
        env:
          ACCEPT_EULA: 1
          SA_PASSWORD: P@ssw0rd
        ports:
          - 1433:1433

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: 'wait for sql to be ready'
        run: |
          set +o pipefail +e
          for i in {1..60};
          do
              sqlcmd -S localhost -U sa -P P@ssw0rd -d master -Q "select getdate()"
              if [ $? -eq 0 ]
              then
                  echo "sql server ready"
                  break
              else
                  echo "not ready yet..."
                  sleep 1
              fi
          done
          set -o pipefail -e
      # deploy the sql project
      - uses: azure/sql-action@v1.3
        with:
          connection-string: "Server=localhost;Initial Catalog=contoso-insurance;User ID=sa;Password=P@ssw0rd;"  # the local connection string
          project-file: './sql/build2022.sqlproj' # the SQLproj file
      
      - name: run a query
        run: |
          sqlcmd -S localhost -U sa -P P@ssw0rd -d contoso-insurance -Q "SELECT MonthCode, MonthName, Year, Month, CSAT from reporting.CSATByMonth for json auto"

```
