### ISSUE TITLE
arguments not passing variable to sqlcmd

### ISSUE THREAD

**Issue by Don-Chambers** [Azure/sql-action#144]
I have the following action:
```
uses: azure/sql-action@v2
with:
  connection-string: ${{ secrets.CONNECTION_STRING }}
  path: './test.sql'
  arguments: '-v client_name="testname"'
```
According to the documentaiton, this should pass the arguments to the SQLCMD utility but it's not working.  The line below shows the sqlcmd statement from the logs and there is no -v option.
`sqlcmd -S sqldb-***.database.windows.net -d Auth -U *** -i ./test.sql`

I also get this error when the script runs.
`'client_name' scripting variable not defined.`

This is what the [documentation ](https://github.com/Azure/sql-action#arguments)says:
go-sqlcmd: go-sqlcmd parameters are passed to the go-sqlcmd utility from the arguments property. This enables SQLCMD variables -v to be passed to scripts as seen in the sqlcmd documentation.
