### ISSUE TITLE
Getting Failed to add firewall rule error during SQL DB deployment using GitHub Hosted Runner

### ISSUE THREAD

**Issue by tmfahim** [Azure/sql-action#174]
Getting Failed to add firewall rule error during SQL DB deployment using GitHub Hosted Runner although 'Allow Azure Services And resources to access this server" is checked in the SQL server

Error: Failed to add firewall rule. Unable to detect client IP Address. Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user 'MCSSQLADMIN'..
 Error: The process 'C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\SQLCMD.exe' failed with exit code 1

**Comment by zijchen** [comment]
Could you share a snippet of your yaml definition with the Azure login and sql-action tasks?

**Comment by dzsquared** [comment]
The error portion `Error: Microsoft ODBC Driver 17 for SQL Server` suggests this is an older version of sql-action.  Will you try your pipeline with an updated version (v2.1.1 is latest)

**Comment by tmfahim** [comment]
Hi there,
Please see below.

  release:

    # Set the dependency for the build job

    needs: BuildDacpac

    # The type of runner that the job will run on

   runs-on: windows-latest

    environment: PRD

    permissions:

      id-token: write

      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:

     - name: download SQL Pool artifact

        # Downloads artifact to dacpac folder

        uses: ***@***.******@***.***>

        with:

          name: SQLPool

      # Login using Azure credentials

      - name: 'OIDC Login to Azure Public Cloud with AzPowershell'

        uses: ***@***.***

        with:

         client-id: ${{ secrets.CLIENT_ID }}

         subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

         tenant-id: ${{ secrets.TENANT_ID }}

         enable-AzPSSession: true

      - name: Azure SQL Deploy

        uses: ***@***.******@***.***>

        with:

          # Name of the SQL Server

          server-name: ${{ vars.SQL_SERVER }}

          # The connection string, including authentication information for the Azure SQL Database

          connection-string: '${{ secrets.AZURE_SQL_CONNECTION_STRING }}'

          # Path to the Azure SQL database dacpac file

          dacpac-package: 'uda-mcs-sql-db-cloud.dacpac'

          # Additional arguments

          arguments: '/p:IncludeCompositeObjects=true'



With Regards,

Fahim Amin
Data Architect, Heavy Oil
Upstream Digital Accelerator
Ph.: +1-587-476-2540
Cell: +1-403-860-1124
***@***.******@***.***>

ExxonMobil Business Support Centre Canada ULC
505 Quarry Park Blvd. SE
Central Building- C2A.126
Calgary AB T2C 5N1

**Comment by zijchen** [comment]
Formatted yml:
```yml
  release:
    # Set the dependency for the build job
    needs: BuildDacpac

    # The type of runner that the job will run on
   runs-on: windows-latest
    environment: PRD
    permissions:
      id-token: write
      contents: read

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: download SQL Pool artifact
        # Downloads artifact to dacpac folder
        uses: ***@***.******@***.***>
        with:
          name: SQLPool

      # Login using Azure credentials
      - name: 'OIDC Login to Azure Public Cloud with AzPowershell'
        uses: ***@***.***
        with:
         client-id: ${{ secrets.CLIENT_ID }}
         subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
         tenant-id: ${{ secrets.TENANT_ID }}
         enable-AzPSSession: true

      - name: Azure SQL Deploy
        uses: ***@***.******@***.***>
        with:
          # Name of the SQL Server
          server-name: ${{ vars.SQL_SERVER }}
          # The connection string, including authentication information for the Azure SQL Database
          connection-string: '${{ secrets.AZURE_SQL_CONNECTION_STRING }}'
          # Path to the Azure SQL database dacpac file
          dacpac-package: 'uda-mcs-sql-db-cloud.dacpac'
          # Additional arguments
          arguments: '/p:IncludeCompositeObjects=true'

```

**Comment by zijchen** [comment]
Looks like the Actions steps themselves were masked (maybe the email client thought they were email addresses), but as @dzsquared mentioned, could you try using sql-action@v2.1.1?

```yml
      - name: Azure SQL Deploy
        uses: azure/sql-action@v2.1.1
        with:
          # The connection string, including authentication information for the Azure SQL Database
          connection-string: '${{ secrets.AZURE_SQL_CONNECTION_STRING }}'
          # Path to the Azure SQL database dacpac file
          path: 'uda-mcs-sql-db-cloud.dacpac'
          action: 'Publish'
          # Additional arguments
          arguments: '/p:IncludeCompositeObjects=true'
```
