### ISSUE TITLE
Failed to add firewall rule

### ISSUE THREAD

**Issue by adobryn** [Azure/sql-action#205]
I'm trying to deploy to Azure DB from a runner VM within the same subscription.

For database this option "Allow public access from any Azure service within Azure to this server" is active but the GitHub Action still can't get past the firewall with the error message

`Failed to add firewall rule. Unable to detect client IP Address.`

Adding a public IP of the runner VM to firewall rules did not help. Also I can connect to the database using `psql` from the runner direct, and with `az postgres flexible-server connect ` as well.

Is it possible to disable automatically adding new firewall rules in the action?

here is the code:
```
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - uses: azure/sql-action@v2.2.1
        with:
          connection-string: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
          path: './project/projectsqlproj'
          action: 'publish'
``` 

Connection string is built like this:
```
Server=<dbname>.postgres.database.azure.com,<port number>;Initial Catalog=<name>; User ID=<username>; Password=<password>; Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
```

**Comment by adobryn** [comment]
Ok, seems that the problem was in the connection string. With 
`Server=<dbname>.postgres.database.azure.com;Database=postgres;Port=5432;User Id=<username>;Password=<password>;Ssl Mode=Require;` I've got another error message that doesn't concert the github ation

**Comment by benjamin-hodgson** [comment]
+1 to this, I'd like a way to opt out of the automatic firewall behaviour. An option in the action yaml would suit me, something like this:

```yaml
uses: azure/sql-action@v2.2.1
  with:
    connection-string: ...
    path: ...
    action: Publish
    configure-firewall: false
```
