### ISSUE TITLE
Error: No credentails found. Add an Azure login script before this action.

### ISSUE THREAD

**Issue by joe-schmirler** [Azure/sql-action#209]
Using Azure/sql-action@v2.2 to deploy scripts to on-premises SQL Server 2019 using a sql authenticated account.  I am not using Azure in any way.  I can have a successful deploy of a .sql script one run, and the next run that same script/execution can fail, and keep failing reruns, and then just randomly be successful.

The error is:
Error: No credentails found. Add an Azure login script before this action.

"credentails" is not a spelling error on my end, that is the copy/pasted error from GitHub Actions workflow.  In bin/main.js, you can search for "credentails" to see the chunk of code that it is erroring due to something within the code.

I find it strange behavior that with the exact same setup one run will be successful, the next one will fail (and sometimes fail dozens of times in a row), and then randomly will be successful again.  

Has anyone else seen this behavior/error message?  

```yaml
- name: Deploy to Target
        uses: Azure/sql-action@v2.2
        with:
          connection-string: "${{ secrets.CONNECTION_STRING }}"
          path: './sqlscripts/dummy.sql'
          arguments: -b
```
