### ISSUE TITLE
Issues with Nordic Characters 

### ISSUE THREAD

**Issue by stefkla** [Azure/sql-action#223]
Hi ! 
My action looks like this: 
```
    - name: Deploy Post-script Database 
      uses: Azure/sql-action@v1
      with: 
        server-name: ${{steps.ServerName}}
        connection-string: ${{...sql-pipelineconfig-connectionstring}}
        sql-file: ${{ github.workspace }}\Path\to\script\file.sql
```

The issue I am facing is that nordic characters - ÅÆØ - are replaced by garbage symbols, E.g: 
'Kårstø' becomes 'KÃ…RSTÃ˜'

The Collation is set correctly on the Azure SQL database, and we can run the script manually in in SQL Server Management Studio to get the correct output. 

Tried a couple of different things, among others verifying database collation, column types, that the generated files have the correct UTF encoding. 
The last thing I can think of is that it is possibly an issue with the action
