### ISSUE TITLE
Build fails when running ubuntu-latest

### ISSUE THREAD

**Issue by jakeclaypool** [Azure/sql-action#252]
When running on ubuntu-22.04 the build runs:

runs-on: ubuntu-22.04

However, with the Ubuntu latest, it fails with the following:

There was an error when attempting to execute the process 'sqlpackage'. This may indicate the process failed to start. Error: spawn sqlpackage ENOENT

**Comment by DavidNorena** [comment]
Temporariy workaround

Run this command in a previous step

```
  steps:
    - name: Restore dotnet tools
      shell: bash
      run: dotnet tool install --tool-path /usr/local/bin/ microsoft.sqlpackage
```
