### ISSUE TITLE
sql-action failing to deploy to Azure Gov for Synapse Workspace, but works in Azure Commercial

### ISSUE THREAD

**Issue by RKSelvi** [Azure/sql-action#31]
I am trying to deploy dacpac to Synapse Workspace. This works in Azure Commercial but not in Azure Gov. I am getting this error below.

**Error: Unable to get details of SQL server servername.sql.azuresynapse.usgovcloudapi.net. Sql server servername.sql.azuresynapse.usgovcloudapi.net' was not found in the subscription.**

- uses: azure/sql-action@v1
      with:
        server-name: "${{ env.DB_Server_Name }}.sql.azuresynapse.usgovcloudapi.net"
        connection-string: "Server=tcp:${{ env.DB_Server_Name }}.sql.azuresynapse.usgovcloudapi.net,1433;Initial Catalog=${{ env.DB_Name }};Persist Security Info=False;User ID=${{ env.SQL_ADMIN_USER_NAME }};Password=${{ env.SQL_ADMIN_USER_PSWD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
        dacpac-package: ${{ env.DACPAC_Path }}
        arguments: "/Variables:DataLakeAccessKey=\"${{ env.DATA_LAKE_ACCESS_KEY }}\" /Variables:DataLakeAccessId=\"${{ env.DATA_LAKE_ACCESS_ID }}\" /Variables:DataLakeEncryptionMasterKey=\"${{ env.DATA_LAKE_ENCRYPTION_MASTER_KEY }}\""

**Questions:**
Is it possible that some resource providers are not exposed in Azure Gov?
I tried to deploy dacpac package via sqlpackage.exe and that works. Only the issue with this GitHub action.

**Comment by AmrutaKawade** [comment]
@RKSelvi just to confirm are you specifying `AzureUSGovernment` option when using Azure/login action before this action.

Refer this document for how to connect to Azure Gov Cloud

https://github.com/Azure/login#sample-to-connect-to-azure-us-government-cloud

**Comment by RKSelvi** [comment]
Yes @AmrutaKawade. This is the existing pipeline with sql-action, only thing changed is deploying to Synapse workspace/SQL pool vs SQL server/Dedicated SQL pool

I overcame to directly to add/remove firewall and execute sqlpackage.exe directly. When I added /removed firewall the provider namespace for synapse workspace had to be updated. It is not Az**Sql**FirewallRule but Az**Synapse**FirewallRule. I am not sure if that could cause issue in sql-action GH action

New-AzSynapseFirewallRule
Remove-AzSynapseFirewallRule

**Comment by AmrutaKawade** [comment]
@RKSelvi you mentioned that deploy to Azure Commercial is working. Just to confirm deploying of Synapse workspace is working for Azure Commercial?

**Comment by RKSelvi** [comment]
Yes @AmrutaKawade. sql-action works for Synapse workspace in Azure Commercial. Only in Azure Gov it was giving an error.

**Comment by AmrutaKawade** [comment]
Oh this is strange. 
this is failing at this step

https://github.com/Azure/sql-action/blob/7da069cac12bdd00ebdd506f7da9f1e79042a81d/src/AzureSqlResourceManager.ts#L133

since this API did not return any servers

https://github.com/Azure/sql-action/blob/7da069cac12bdd00ebdd506f7da9f1e79042a81d/src/AzureSqlResourceManager.ts#L114

I think it should have failed for Azure Commercial as well since provider is different (Microsoft.Synapse) for Synapse

can you run these commands for both Azure Gov cloud and Azure Commercial and share logs for `List SQL Servers` step?


```
- name: Login to Azure US Gov Cloud with CLI
     uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_US_GOV_CREDENTIALS }}
          environment: 'AzureUSGovernment'
          enable-AzPSSession: false

- name: 'List SQL Servers'
     run: |
          az account show
          az cloud show
          curl -X GET https://management.azure.com/subscriptions/{subscriptionId}/providers/Microsoft.Sql/servers?api-version=2015-05-01-preview

- name: 'Connect to server
     uses: azure/sql-action@v1
       with:
           server-name: "${{ env.DB_Server_Name }}.sql.azuresynapse.usgovcloudapi.net"
           connection-string: "Server=tcp:${{ env.DB_Server_Name }}.sql.azuresynapse.usgovcloudapi.net,1433;Initial Catalog=${{ env.DB_Name }};Persist Security Info=False;User ID=${{ env.SQL_ADMIN_USER_NAME }};Password=${{ env.SQL_ADMIN_USER_PSWD }};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"
           dacpac-package: ${{ env.DACPAC_Path }}
           arguments: "/Variables:DataLakeAccessKey="${{ env.DATA_LAKE_ACCESS_KEY }}" /Variables:DataLakeAccessId="${{ env.DATA_LAKE_ACCESS_ID }}" /Variables:DataLakeEncryptionMasterKey="${{ env.DATA_LAKE_ENCRYPTION_MASTER_KEY }}""

```
