### ISSUE TITLE
feature request : Add support of Xml PublishProfile configuration

### ISSUE THREAD

**Issue by didaskein** [Azure/sql-action#32]
Hi,

Could you add the Xml **PublishProfile** configuration as an input of the Github action ?

For example what we have for Azure Devops : 
```
  - task: SqlAzureDacpacDeployment@1
    displayName: "Execute Azure SQL : DacpacTask"
    inputs:
      azureSubscription: "${{parameters.serviceConnection}}"
      AuthenticationType: connectionString
      ConnectionString: "$(kv-SQL-ConnectionString)"
      DacpacFile: "$(Pipeline.Workspace)/drop/SQL/bin/Release/.Database.dacpac"
      PublishProfile: "$(Pipeline.Workspace)/drop/SQL/Profile.publish.xml" 
```

The kind of stuff we can configure in the publish profile : 
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <IgnoreIdentitySeed>False</IgnoreIdentitySeed>
    <IgnoreColumnCollation>False</IgnoreColumnCollation>
    <IncludeTransactionalScripts>True</IncludeTransactionalScripts>
    <CreateNewDatabase>False</CreateNewDatabase>
    <BackupDatabaseBeforeChanges>False</BackupDatabaseBeforeChanges>
    **<BlockOnPossibleDataLoss>False</BlockOnPossibleDataLoss>**
    <NoAlterStatementsToChangeCLRTypes>False</NoAlterStatementsToChangeCLRTypes>
    <ProfileVersionNumber>1</ProfileVersionNumber>
    <ScriptDatabaseOptions>False</ScriptDatabaseOptions>
    <IncludeCompositeObjects>True</IncludeCompositeObjects>
    <TargetTimeout>4500</TargetTimeout>
    <IgnoreNotForReplication>True</IgnoreNotForReplication>
    <IgnoreFullTextCatalogFilePath>True</IgnoreFullTextCatalogFilePath>
    <VerifyDeployment>True</VerifyDeployment>
    <IgnorePartitionSchemes>True</IgnorePartitionSchemes>
    <DeployDatabaseInSingleUserMode>True</DeployDatabaseInSingleUserMode>
    <!--Drop and Exclude Objects-->
    <DropObjectsNotInSource>False</DropObjectsNotInSource>
    <IgnoreRoleMembership>True</IgnoreRoleMembership>
    <IgnoreUserSettingsObjects>True</IgnoreUserSettingsObjects>
    <IgnoreUserLoginMappings>True</IgnoreUserLoginMappings>
    <DoNotDropUsers>True</DoNotDropUsers>
    <IgnorePermissions>True</IgnorePermissions>
    <DoNotDropLogins>True</DoNotDropLogins>
    <DoNotDropLinkedServers>True</DoNotDropLinkedServers>
  </PropertyGroup>
</Project>
```

Thank you,
Kind regards.
