### ISSUE TITLE
[Feature Request] skip add firewall rule 

### ISSUE THREAD

**Issue by mayong43111** [Azure/sql-action#66]
Hi,
    I have a customer who has very strict access, they don't want to open a firewall every time and they used self-hosted. could you add a parameter like as.

```
  skipFirewallSetting:
    description: 'Parameters which skip Firewall Setting'
    required: false
    default: 'false'
```

```
        let skipFirewallSetting = (core.getInput('skipFirewallSetting') != 'true');
        
        if(skipFirewallSetting){
            const runnerIPAddress = await SqlUtils.detectIPAddress(inputs.serverName, inputs.connectionString);
            if(runnerIPAddress) {
                let azureResourceAuthorizer = await AuthorizerFactory.getAuthorizer();
                let azureSqlResourceManager = await AzureSqlResourceManager.getResourceManager(inputs.serverName, azureResourceAuthorizer);
                firewallManager = new FirewallManager(azureSqlResourceManager);
                await firewallManager.addFirewallRule(runnerIPAddress);
            }
        }
```
