### ISSUE TITLE
Unable to authenticate to Azure SQL Server via service principal

### ISSUE THREAD

**Issue by ssulei7** [Azure/sql-action#78]
Hi,

Not sure if this is the correct issue template to use, but I am currently working with a customer to build out workflows to deploy DACPACs into their Azure SQL instance. We have created a service principal, but we keep bumping into the following error:

`Failed to add firewall rule. Unable to detect client IP address.`

Currently, our action is configured as follows:

```yaml
      - name: Azure SQL Deploy
        uses: Azure/sql-action@v1.2
        with:
          connection-string: 'Server=${{ env.serverName}};User ID=***;Password=***;Initial Catalog=${{ env.catalog_name }} ;Authentication=ActiveDirectoryServicePrincipal;'
          dacpac-package: MyDacpac.dacpac
          arguments: '/p:IncludeCompositeObjects=true' 
```

Are service principals currently not supported by this task?
