### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by gsuttie** [Azure/sql-action#8]
Any idea how I figure out the firewall part:- 

Failed to add firewall rule. Unable to detect client IP Address. Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Named Pipes Provider: Could not open a connection to SQL Server [53]. .

**Comment by gsuttie** [comment]
Ignore this issue as I had a connection string issue

**Comment by julian-code** [comment]
Hey @gsuttie I actual have the same issue now. What did you do in your connection string?

**Comment by gsuttie** [comment]
I didnt do anything in the connection string, go to the azure sql server and then click on set server firewall and then click on add client Ip at the top - that should sort your issue.

**Comment by julian-code** [comment]
I still get the same problem. You can see the action I run here: 

https://github.com/julian-code/makersofdenmark/runs/1286102147

**Comment by julian-code** [comment]
I managed to solve it. The server-name input is the servername from azure. Thats the full server name, not just what you called your server.

The full name is something like <servername>.database.windows.net.

```
    - name: Migrate database
      uses: azure/sql-action@v1
      with:
        server-name: SERVERNAMEFROMAZURE
        connection-string: ${{ secrets.AZURE_SQL_SERVER_CONNECTION_STRING }}
        sql-file: './migration.sql'
```
