### ISSUE TITLE
support for user authentication without access to master db

### ISSUE THREAD

**Issue by mabster** [Azure/sql-action#89]
Hi gang,

I'm trying to use Azure/sql-action in the "deploy" phase of my workflow when deploying an ASP.NET Core app to Azure.

My Azure SQL server definitely has "Allow Azure services and resources to access this server" set to "Yes", but when my workflow runs I get the following error:

Error: Failed to add firewall rule. Unable to detect client IP Address. Sqlcmd: Error: Microsoft ODBC Driver 17 for SQL Server : Login failed for user '(redacted)'..

My code looks like this:

   - name: Apply EF migration script
        uses: Azure/sql-action@v1
        with:
          server-name: (my server name).database.windows.net
          connection-string: ${{ secrets.CONNECTIONSTRING_PUCKA }}
          sql-file: ./migrate.sql

In the server-name attribute I've tried it with and without the "tcp:" prefix (which is in the connection string) but I get the same error both ways.

Your README says if I have "allow azure services" set to "yes" then I should be fine. Am I doing something wrong?

**Comment by mabster** [comment]
Hmm I redacted the username and server name in my post above but I used angle brackets so GitHub removed the word "redacted" entirely. Rest assured the user id is set in the connection string. :)

**Comment by mabster** [comment]
Have updated to the latest version but still getting the same error. My action looks like this now:

```
 - name: Apply EF migration script
        uses: Azure/sql-action@v1.2
        with:
          connection-string: ${{ secrets.CONNECTIONSTRING_PUCKA }}
          sql-file: ./migrate.sql
```
